name: Manual Trigger Workflow

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
        - name: Step one
        run: echo "Step 1 complete"
        -name: Step two
        run: echo "Step 2 complete"
        
    job2:
        needs: job1
        runs-on: ubuntu-latest

        steps:
        - name: Run Cowsays action
        uses: mscoutermarsh/cowsays-action@master
        # The 'with' block includes parameters that the workflow will pass
        # to this action. Parameters are all in key-value format.
        with:
          text: 'Ready for prod--ship it!'
          color: 'magenta'
